name: Generate and Deploy HTML

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00PM UTC every day
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build HTML
      run: cargo run --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
